[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx.conf"
keys = [
  "/helgoboss/org/preview/fqdn",
  "/helgoboss/org/live/fqdn",
  "/helgoboss/org/ssl/cert/name",
  "/benjamin/klum/com/preview/fqdn",
  "/benjamin/klum/com/live/fqdn",
  "/benjamin/klum/com/ssl/cert/name"
]
owner = "root"
mode = "0644"